### list
GET http://localhost:9129/list?app=app1&env=dev&ns=public

### list
GET http://localhost:9129/version?app=app1&env=dev&ns=public

### update
POST http://localhost:9129/update?app=app1&env=dev&ns=public
Content-Type: application/json

{
  "kfc.a": "dev300",
  "kfc.c": "cc200",
  "kfc.d": "dd200",
  "kfc.f": "ff200"
}

### demo 8888
GET http://localhost:8081/demo